export const listNamePersonnels = [
  "Sri Anggoro, S.P., M.M.",
  "Inggar Dwi Wahyuni, SE",
  "Novi Susianti, S.Pi., M.Si",
  "Noviana Dewi, S.Pi, M.Tr.Pi",
  "Muji Dwi Saptono, A.Pi, MM",
  "Kismono Kudoasmoro, S.ST.Pi",
  "Fajri Wahyuni, S.Si",
  "Moch. Farez Dwi Sentanu, SE",
  "Susiana, SE",
  "Donie Saktya Dharma, SE",
  "Pramudyananto, ST",
  "Yunari Sigit Pramono, SE",
  "Galih Pratomo Suwatno, A.Md",
  "Ari Nuryatman, A.Md",
  "Sandi Nurcahyo Mukti Wibowo, A.Md. Pi",
  "Eka Sustiyaningsih, A.Md",
  "Dicky Afriyanto",
  "Dwi Wardani, A.Md",
  "Yayan Heryanto",
  "Ustim",
  "Irwanto",
  "Nurjali",
  "Salbiyah",
  "Bayu Adi Nugroho, SE",
  "Nur Azimah Rozaldi, SE",
  "Nurul Inayah, SE",
  "Indramawan",
  "Septian Mardiyana, S.I.Kom",
  "Doni Wahyudi",
  "Siwi Hasto Wasono Budi",
  "Mochamad Rukayat",
  "Rohaya",
  "Onik Tarsonik, S.Kom",
  "Eka Setiawati, S.Ak",
  "Iwan Sumantri",
  "Kurniawan",
  "RR Mutiara Kusuma Suri Iswari, S.Tr.Pi",
  "Rohidin",
  "Samang",
  "Tedy Putranto",
  "Rusdianto",
  "Dede Hermawan",
  "Uden Rahmat Hidayat",
];
